### PR TITLE
Added create_value_request

### PR DESCRIPTION
**Pull request by xorrbit**
I added a method to create a value request message.

### CODE REVIEW

**Comment by Nitrodist** [comment]
Upvoting the hell out of this +1 +1 :thumbsup: +1 +1 :thumbsup: +1 +1 :thumbsup:

**Comment by fchorney** [comment]
Upvoting as well! +1 +1 +1 +1

**Comment by burke** [comment]
Sorry, I get a shitload of github notifications from work so I don't monitor my github inbox as closely as I should.

**Comment by burke** [comment]
I started in on refactoring this and the rest of the library, but haven't merged it to master as I haven't written tests.

https://github.com/burke/mintchip/tree/refactoring/lib/mintchip

https://github.com/burke/mintchip/blob/refactoring/lib/mintchip/value_request_message.rb

https://github.com/burke/mintchip/blob/refactoring/lib/mintchip/mintchip_message.rb

Probably best to work off of this if you're going to be contributing to the library again before I get around to writing tests and releasing it.

EDIT: Nevermind, I wrote a test for the ASN stuff and merged it to master. It appears to work, but let me know if I broke it.

**Comment by xorrbit** [comment]
Nice, looks great.

FYI I also started on validate_value_message (validate as much as possible without talking to the mintchip server, as per http://developer.mintchipchallenge.com/devguide/developing/common/message-validation.html):
https://github.com/xorrbit/mintchip/blob/validate-value-message/lib/mintchip.rb

Feel free to rip stuff out of there, I'm not sure I'll have time to work on this much this week.

**Comment by burke** [comment]
Very awesome. I'll dig into that next time I want to avoid more real work.

**Pull request merged**
